#!/bin/bash

photo=$1
outname=snap-${photo}

# TODO: get the original size of the image

# Dimensions of the picture (in pixels)
w=1520.0
h=1000.0

# needed crop to pass from 4:3 to 7.6:5
bcrop=`echo "0.1228 * $h" | bc`

# Size of the borders
# - top:
r_border_t=0.06
# - bottom:
r_border_b=0.06
# - left:
r_border_l=0.159
# - right:
r_border_r=0.033

# Calculate white borders based on the percentages
border_t=`echo "$r_border_t * $h" | bc`
border_b=`echo "$r_border_b * $h" | bc`
border_l=`echo "$r_border_l * $w" | bc`
border_r=`echo "$r_border_r * $w" | bc`

# Size of the regions to be cropped in the image
# - top:
r_crop_t=0.05
# - bottom:
r_crop_b=0.055
# - left:
r_crop_l=0.035
# - right:
r_crop_r=0.035

# cropped regions of the original image
# - top:
crop_t=`echo "$r_crop_t * $h" | bc`
# - bottom:
crop_b=`echo "$r_crop_b * $h" | bc`
# - left:
crop_l=`echo "$r_crop_l * $w" | bc`
# - right:
crop_r=`echo "$r_crop_r * $w" | bc`

# size of the inner image
ww=`echo "$w - $border_l - $border_r" | bc`
hh=`echo "$h - $border_t - $border_b" | bc`

# Process the image with imageMagick
convert ${photo} -geometry ${h}x${h} -crop +0-0 \
        -geometry ${ww}x${hh} \
        -crop -${crop_r}+${crop_t} \
        -crop +${crop_l}-${crop_b} \
        aux_1.jpeg

convert -size ${w}x${h} xc:white \
    aux_1.jpeg -geometry ${ww}x${hh}+${border_l}+${border_t} -composite ${outname}

# Delete temporary files
rm aux_*.jpeg
