#!/bin/bash

# Output file name
outname=photoboot-snap.jpeg

# Separation between images (in pixels)
insep=30

montage \( $1 -geometry 50%x50% \) \
        \( $2 -geometry 50%x50% \) \
        \( $3 -geometry 50%x50% \) \
        \( $4 -geometry 50%x50% \) \
        -tile 2x2 -geometry +${insep}+${insep} aux_1.jpeg

# add extra border on the outside
convert aux_1.jpeg -bordercolor white -border ${insep} ${outname}

rm aux_*.jpeg

